spring.application.name=intershop

server.port=8080

spring.sql.init.mode=always

spring.r2dbc.pool.enabled=true
spring.r2dbc.pool.initial-size=10
spring.r2dbc.pool.max-size=50
spring.r2dbc.pool.max-idle-time=30s
spring.r2dbc.pool.max-life-time=10m
spring.r2dbc.pool.validation-query=SELECT 1

logging.level.ru.yandex.practicum=DEBUG
logging.level.org.springframework.web=DEBUG

#redis
spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}
# TTL по умолчанию для кешей
spring.cache.redis.time-to-live=${REDIS_TTL}

#intershop-payment-server
intershop-payment.url=${INTERSHOP_PAYMENT_URL}

#authentication repository
spring.session.store-type=redis

#keycloak for client
spring.security.oauth2.client.provider.keycloak.issuer-uri=http://localhost:8085/realms/master # Адрес сервера авторизации для получения токена
spring.security.oauth2.client.registration.provider=keycloak
spring.security.oauth2.client.registration.authorizationGrantType=client_credentials
spring.security.oauth2.client.registration.client-id=intershop
spring.security.oauth2.client.registration.client-secret=KqVZWIkplcqe6oM8DjPkiutdZFkLZtC6
spring.security.oauth2.client.registration.scope=profile
spring.security.oauth2.client.registration.clientAuthenticationMethod=client_secret_post # Способ передачи секрета
