drop table if exists users cascade;
drop table if exists items cascade;
drop table if exists cart_positions cascade;
drop table if exists orders cascade;
drop table if exists roles cascade;

CREATE TABLE IF NOT EXISTS users (

    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name            VARCHAR(255) NOT NULL,
    email           VARCHAR(255) NOT NULL,
    birth_date      TIMESTAMP,
    reg_date        TIMESTAMP,
    password        VARCHAR(255) NOT NULL,

    CONSTRAINT      pk_user PRIMARY KEY (id),

    CONSTRAINT      UQ_USER_NAME UNIQUE (name),

    CONSTRAINT      UQ_USER_EMAIL UNIQUE (email)
    );

CREATE TABLE IF NOT EXISTS items (

    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title           VARCHAR(255) NOT NULL,
    description     VARCHAR(255) NOT NULL,
    image_url       VARCHAR(1025),
    amount_in_stock INTEGER NOT NULL,
    price           INTEGER NOT NULL,

    CONSTRAINT      pk_item PRIMARY KEY (id),

    CONSTRAINT      UQ_ITEM_TITLE UNIQUE (title)
    );

CREATE TABLE IF NOT EXISTS cart_positions (

    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id         BIGINT NOT NULL,
    item_id         BIGINT NOT NULL,
    amount          INTEGER NOT NULL,
    item_price      INTEGER NOT NULL,

    CONSTRAINT      pk_cart PRIMARY KEY (id),

    CONSTRAINT  fk_cart_user_id
        FOREIGN KEY (user_id)
            REFERENCES users (id)
            ON DELETE CASCADE,

    CONSTRAINT  fk_cart_item_id
        FOREIGN KEY (item_id)
            REFERENCES items (id)
            ON DELETE CASCADE
    );

CREATE TABLE IF NOT EXISTS orders (

    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    order_uid       VARCHAR(255) NOT NULL,
    user_id         BIGINT NOT NULL,
    item_id         BIGINT NOT NULL,
    amount          INTEGER NOT NULL,
    item_price      INTEGER NOT NULL,
    total_price     INTEGER NOT NULL,

    CONSTRAINT      pk_order PRIMARY KEY (id),

    CONSTRAINT  fk_order_user_id
        FOREIGN KEY (user_id)
            REFERENCES users (id)
            ON DELETE CASCADE,

    CONSTRAINT  fk_order_item_id
        FOREIGN KEY (item_id)
            REFERENCES items (id)
            ON DELETE CASCADE
    );

CREATE TABLE IF NOT EXISTS roles (

    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id    BIGINT                                  NOT NULL,
    role_name  VARCHAR(255)                            NOT NULL,

    CONSTRAINT pk_role PRIMARY KEY (id),

    CONSTRAINT fk_role_user_id
        FOREIGN KEY (user_id)
            REFERENCES users (id)
            ON DELETE CASCADE
    );