spring.application.name=intershop

server.port=8080

spring.sql.init.mode=always

spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/test-db
spring.datasource.username=postgres
spring.datasource.password=iamroot

logging.level.ru.yandex.practicum=DEBUG

logging.level.org.hibernate.SQL=TRACE
logging.level.org.hibernate.type=INFO
