CREATE TABLE IF NOT EXISTS users (

    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name            VARCHAR(255) NOT NULL,
    email           VARCHAR(255) NOT NULL,
    birth_date      TIMESTAMP,
    reg_date        TIMESTAMP,
    password        VARCHAR(255) NOT NULL,

    CONSTRAINT      pk_user PRIMARY KEY (id),

    CONSTRAINT      UQ_USER_NAME UNIQUE (name),

    CONSTRAINT      UQ_USER_EMAIL UNIQUE (email)
    );

insert into users(name, email, birth_date, reg_date, password)
values ('User 1',
        'user1@email.net',
        null,
        null,
        'password');

CREATE TABLE IF NOT EXISTS items (

    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title           VARCHAR(255) NOT NULL,
    description     VARCHAR(255) NOT NULL,
    image_url       VARCHAR(1025),
    amount          INTEGER NOT NULL,
    price           INTEGER NOT NULL,

    CONSTRAINT      pk_item PRIMARY KEY (id),

    CONSTRAINT      UQ_ITEM_TITLE UNIQUE (title)
    );

insert into items(title, description, image_url, amount, price)
values ('Item 1',
        'simple Item 1',
        'https://printing-t-shirts.podaru.ru/assets/images/products/595/1847307tif1000x1000.jpg',
        100,
        1000);

insert into items(title, description, image_url, amount, price)
values ('Item 2',
        'simple Item 2',
        'https://avatars.mds.yandex.net/get-mpic/7067087/img_id7321255958679773840.jpeg/orig',
        100,
        2000);

insert into items(title, description, image_url, amount, price)
values ('Item 3',
        'simple Item 3',
        'https://cdn1.ozone.ru/s3/multimedia-h/6228972941.jpg',
        100,
        3000);

CREATE TABLE IF NOT EXISTS carts (

    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id         BIGINT NOT NULL,
    item_id         BIGINT NOT NULL,
    amount          INTEGER NOT NULL,
    item_price      INTEGER NOT NULL,
    total_price     INTEGER NOT NULL,

    CONSTRAINT      pk_cart PRIMARY KEY (id),

    CONSTRAINT  fk_cart_user_id
        FOREIGN KEY (user_id)
            REFERENCES users (id)
            ON DELETE CASCADE

    CONSTRAINT  fk_cart_item_id
        FOREIGN KEY (item_id)
            REFERENCES items (id)
            ON DELETE CASCADE
    );

CREATE TABLE IF NOT EXISTS orders (

    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    order_uid       VARCHAR(255) NOT NULL,
    user_id         BIGINT NOT NULL,
    item_id         BIGINT NOT NULL,
    amount          INTEGER NOT NULL,
    item_price      INTEGER NOT NULL,
    total_price     INTEGER NOT NULL,

    CONSTRAINT      pk_order PRIMARY KEY (id),

    CONSTRAINT  fk_order_user_id
        FOREIGN KEY (user_id)
            REFERENCES users (id)
            ON DELETE CASCADE

    CONSTRAINT  fk_order_item_id
        FOREIGN KEY (item_id)
            REFERENCES items (id)
            ON DELETE CASCADE
    );